name: batighor_jss_management
description: Batighor JSS Management teacher app (Teachers)
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter: { sdk: flutter }
  http: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_spinkit: ^5.2.0
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: ^0.13.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon.png
    - assets/images/Splash.gif
    - assets/images/loading.gif

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/icon.png
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/icon.png
  branding: assets/images/Splash.gif
  android_12:
    image: assets/images/icon.png
    branding: assets/images/Splash.gif
    color: "#ffffff"
